#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

export LOCAL_BIN="/usr/local/bin"
export OPT_DIR="$HOME/opt/"

init() {
	mkdir -p "$OPT_DIR"
}

which_validate() {
	local name="$1"
	if which "$name" >/dev/null 2>&1; then
		exit 0
	else
		exit 1
	fi
}

wget_dpkg() {
  echo 'hi'
	local download_url="$1"
	local file="$1"
	wget -P /tmp "$download_url"
	sudo dpkg -i "/tmp/$file"
}

init
