#!/usr/bin/env bash

set -CEeuo pipefail
IFS=$'\n\t'
shopt -s extdebug

export LOCAL_BIN="/usr/local/bin"
export OPT_DIR="$HOME/opt/"

SCRIPT_PATH="$(dirname $(realpath $0))"

init() {
	mkdir -p "$OPT_DIR"
}

which_validate() {
	local name="$1"
	if which "$name" >/dev/null 2>&1; then
		exit 0
	else
		exit 1
	fi
}

ensure_installed() {
  local name="$1"
  local not_installed
  set +e
  bash  "$SCRIPT_PATH/$name" "validate"
  not_installed="$?"
  set -e
  if [ "$not_installed" -eq "1" ]; then
    bash  "$SCRIPT_PATH/$name" "install"
  fi
}

wget_dpkg() {
	local download_url="$1"
	local file="$2"
	wget -P /tmp "$download_url"
	sudo dpkg -i "/tmp/$file"
}

apt_package() {
	local action="$1"
	local package_name="$2"
	local command_name="${3:-$2}"

	case "$action" in

	"validate")
		which_validate "$command_name"
		;;

	"install")
		sudo apt install "$package_name"
		;;

	*)
		echo "Bad action used for apt_package: $action"
		exit 1
		;;
	esac
}

init
